---
- name: Converge
  hosts: all
  vars:
    vector_template: vector.toml.j2
    vector_config_file: /etc/vector/vector.toml
    vector_install_from_repo: true
    vector_manage_repo: true
    sources:
      test_source:
        type: demo_logs
        format: json
    transforms:
      parse_logs:
        type: remap
        inputs: ["test_source"]
        source: |
          .parsed = parse_json!(.message)
          .timestamp = now()
          if .parsed.level == "error" {
            .severity = "high"
          } else {
            .severity = "low"
          }
    sinks:
      blackhole:
        type: blackhole
        inputs: ["parse_logs"]
        print_interval_secs: 0
  tasks:
    - name: Include role vector
      ansible.builtin.include_role:
        name: telekom_mms.vector.vector
